# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/pf.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproto/pf.proto\x12\nhelloworld\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0b\x43\x61lcRequest\x12\x10\n\x08password\x18\x01 \x01(\t\"\x1b\n\tCalcReply\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\x7f\n\x07Greeter\x12<\n\x08SayHello\x12\x18.helloworld.HelloRequest\x1a\x16.helloworld.HelloReply\x12\x36\n\x04\x43\x61lc\x12\x17.helloworld.CalcRequest\x1a\x15.helloworld.CalcReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.pf_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=30
  _HELLOREQUEST._serialized_end=58
  _HELLOREPLY._serialized_start=60
  _HELLOREPLY._serialized_end=89
  _CALCREQUEST._serialized_start=91
  _CALCREQUEST._serialized_end=122
  _CALCREPLY._serialized_start=124
  _CALCREPLY._serialized_end=151
  _GREETER._serialized_start=153
  _GREETER._serialized_end=280
# @@protoc_insertion_point(module_scope)
